services:
  plex:
    container_name: plex
    image: ghcr.io/hotio/plex:latest
    restart: unless-stopped
    network_mode: host
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      UMASK: 002
    volumes:
      - ${DOCKER_ROOT}/plex:/config
      - ${MEDIA}:/plex
      - /tmp:/transcode
    devices:
      - /dev/dri:/dev/dri

  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - ${DOCKER_ROOT}/komga:/config
      - ${MEDIA}/manga:/manga
    user: "${PUID}:${PGID}"
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    networks:
      - media_net
      - proxy_net

networks:
  media_net:
    external: true
  proxy_net:
    external: true