name: plex

networks:
  proxy_net:
    external: true

services:
  plex:
    container_name: plex
    image: ghcr.io/hotio/plex:latest
    restart: unless-stopped
    network_mode: host
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      UMASK: 002
    volumes:
      - ${DOCKER_ROOT}/plex:/config
      - ${MEDIA}:/plex
      - /tmp:/transcode
    devices:
      - /dev/dri:/dev/dri

  shoko-server:
    image: shokoanime/server:latest
    container_name: shoko-server
    restart: unless-stopped
    networks:
      - proxy_net
    volumes:
      - ${DOCKER_ROOT}/shoko/server:/home/shoko/.shoko
      - ${MEDIA}:/plex

  shoko-webui:
    image: shokoanime/shoko-webui:latest
    container_name: shoko-webui
    restart: unless-stopped
    networks:
      - proxy_net
    depends_on:
      - shoko-server