services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    network_mode: host
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=America/Montreal
    volumes:
      - ${DOCKER_ROOT}/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN
      - NET_RAW