networks:
  proxy_net:
    external: true

services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=${TZ}
    volumes:
      - ${DOCKER_ROOT}/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - proxy_net