services:
  ubuntu-dev:
    build:
      context: .
      args:
        USERNAME: kaolin
        PASSWORD: kaolin
    container_name: ubuntu-dev
    hostname: ubuntu-dev
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "22222:22"
    volumes:
      - ${DOCKER_ROOT}/ubuntu:/workspace
    environment:
      TZ: ${TZ}