name: downloaders

networks:
  media_net:
    external: true
  proxy_net:
    external: true

services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_ROOT}/downloaders/transmission:/config
      - ${DOWNLOADS}:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    networks:
      - media_net
    restart: unless-stopped

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DELUGE_LOGLEVEL=error
    volumes:
      - ${DOCKER_ROOT}/downloaders/deluge:/config
      - ${DOWNLOADS}:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    networks:
      - media_net
    restart: unless-stopped