name: minecraft

version: '3'
networks:
  proxy_net:
    external: true
services:
  crafty:
    container_name: crafty
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: always
    environment:
        - TZ=${TZ}
        - JVM_OPTS="-Dio.netty.leakDetection.level=DISABLED"
    ports:
    - "8443:8443"           # HTTPS (tcp)
    - "8125:8123"           # Dynmap (tcp)
    - "25560-25570:25560-25570/tcp"
    - "25560-25570:25560-25570/udp"
    volumes:
        - ${DOCKER_ROOT}/minecraft/backups:/crafty/backups
        - ${DOCKER_ROOT}/minecraft/logs:/crafty/logs
        - ${DOCKER_ROOT}/minecraft/servers:/crafty/servers
        - ${DOCKER_ROOT}/minecraft/config:/crafty/app/config
        - ${DOCKER_ROOT}/minecraft/import:/crafty/import
    networks:
        - proxy_net