name: Deploy Homelab Repo

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Run deploy script
        run: |
          chmod +x ~/HomeLab/scripts/deploy-repo.sh
          ~/HomeLab/scripts/deploy-repo.sh