name: Homelab Control

on:
  workflow_dispatch:
    inputs:
      stack:
        description: "Stack path"
        required: true
        default: "media/automation"

      action:
        description: "Compose action"
        required: true
        default: "up"
        type: choice
        options:
          - up
          - down
          - restart
          - pull
          - logs

      allow_core:
        description: "Allow core stacks"
        required: true
        default: "false"
        type: choice
        options:
          - "false"
          - "true"

jobs:
  control:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sync repo
        run: |
          rsync -av --delete \
            --exclude ".git" \
            ./ /srv/homelab/

      - name: Run stack script
        env:
          ALL_SECRETS_JSON: ${{ toJson(secrets) }}
          ALLOW_CORE: ${{ github.event.inputs.allow_core }}
        run: |
          chmod +x /srv/homelab/scripts/*.sh

          /srv/homelab/scripts/compose-stack.sh \
            "${{ github.event.inputs.stack }}" \
            "${{ github.event.inputs.action }}"